document.write('<header>')
document.write('<h2>' + title +'</h2>')
var skills
if (skills){
	document.write(skills)
}

document.write('<nav><ul>')

document.write('<li><a href="../HW1/index.html">HW 1</a></li>')
document.write('<li><a href="../HW2/hw2.html">HW 2</a>')
document.write('<ul><li>')
document.write('<a href="../HW2/pt1.html">HW 2: Part 1</a></li>')
document.write('<li><a href="../HW2/pt2.html">HW 2: Part 2</a></li>')
document.write('<li><a href="../HW2/pt3.html">HW 2: Part 3</a></li>')
document.write('<li><a href="../HW2/pt4.html">HW 2: Part 4</a></li>')
document.write('<li><a href="../HW2/extracredit.html">HW 2: Extra Credit</a></li>')
document.write('</ul></li>')

document.write('<li><a href="../HW3/hw3.html">HW 3</a>')
document.write('<ul>')
document.write('<li><a href="../HW3/pt1.html">HW 3: Part 1</a></li>')
document.write('<li><a href="../HW3/pt2.html">HW 3: Part 2</a></li>')
document.write('<li><a href="../HW3/pt3.html">HW 3: Part 3</a></li>')
document.write('<li><a href="../HW3/pt4.html">HW 3: Part 4</a></li>')
document.write('<li><a href="../HW3/pt5.html">HW 3: Part 5</a></li>')
document.write('<li><a href="../HW3/pt6.html">HW 3: Part 6</a></li>')
document.write('<li><a href="../HW3/extracredit.html">HW 3: Extra Credit</a></li>')
document.write('</ul></li>')


document.write('<li><a href="../HW4/hw4.html">HW 4</a>')
document.write('<ul>')
document.write('<li><a href="../HW4/pt1.html">HW 4: Part 1</a></li>')
document.write('<li><a href="../HW4/pt2.html">HW 4: Part 2</a></li>')
document.write('<li><a href="../HW4/pt3.html">HW 4: Part 3</a></li>')
document.write('<li><a href="../HW4/pt4.html">HW 4: Part 4</a></li>')
document.write('<li><a href="../HW4/pt5.html">HW 4: Part 5</a></li>')
document.write('<li><a href="../HW4/pt6.html">HW 4: Part 6</a></li>')
document.write('<li><a href="../HW4/extracredit.html">HW 4: Extra Credit</a></li>')
document.write('</ul></li>')

document.write('<li><a href="../HW5/hw5.html">HW 5</a>')
document.write('<ul>')
document.write('<li><a href="../HW5/pt1.html">HW 5: Part 1</a></li>')
document.write('<li><a href="../HW5/pt2.html">HW 5: Part 2</a></li>')
document.write('<li><a href="../HW5/pt3.html">HW 5: Part 3</a></li>')
document.write('<li><a href="../HW5/pt4.html">HW 5: Part 4</a></li>')
document.write('<li><a href="../HW5/extracredit.html">HW 5: Extra Credit</a></li>')
document.write('</ul></li>')

document.write('<li><a href="../HW6/hw6.html">HW 6</a></li>')
document.write('<li><a href="../HW7/hw7.html">HW 7</a></li>')
document.write('<li><a href="../HW8/hw8.html">HW 8</a>')
document.write('</li></ul></nav>')
document.write('</header>')